name: delays
channels:
- defaults
- r
dependencies:
- flake8=3.3.0
- ipykernel=4.5.2
- lxml=3.7.2
- nbconvert=5.1.1
- pandas=0.19.2
- pytest=3.0.7
- python=3.6.0
- r::r-base=3.3.2
- r::r-broom=0.4.1
- r::r-dplyr=0.5.0
- r::r-essentials=1.5.2
- r::r-ggplot2=2.2.0
- r::r-glmnet=2.0_5
- r::r-irkernel=0.7.1
- r::r-lubridate=1.6.0
- r::r-magrittr=1.5
- r::r-readr=1.0.0
- r::r-scales=0.4.1
- r::r-tidyr=0.6.0
- requests=2.12.4
- tqdm=4.11.2
