name: delays
channels:
- defaults
- r
dependencies:
- bleach=1.5.0=py36_0
- bzip2=1.0.6=3
- cairo=1.14.8=0
- curl=7.52.1=0
- dbus=1.10.10=0
- decorator=4.0.11=py36_0
- entrypoints=0.2.2=py36_1
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- glib=2.50.2=1
- gmp=6.1.0=0
- gsl=2.2.1=0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- harfbuzz=0.9.39=2
- html5lib=0.999=py36_0
- icu=54.1=0
- ipykernel=4.5.2=py36_0
- ipython=5.1.0=py36_0
- ipython_genutils=0.1.0=py36_0
- ipywidgets=5.2.2=py36_1
- jbig=2.1=0
- jinja2=2.9.4=py36_0
- jpeg=9b=0
- jsonschema=2.5.1=py36_0
- jupyter=1.0.0=py36_3
- jupyter_client=4.4.0=py36_0
- jupyter_console=5.0.0=py36_0
- jupyter_core=4.2.1=py36_0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libiconv=1.14=0
- libpng=1.6.27=0
- libsodium=1.0.10=0
- libtiff=4.0.6=3
- libxcb=1.12=1
- libxml2=2.9.4=0
- libxslt=1.1.29=0
- lxml=3.7.2=py36_0
- markupsafe=0.23=py36_2
- mistune=0.7.3=py36_0
- mkl=2017.0.1=0
- nbconvert=5.1.1=py36_0
- nbformat=4.2.0=py36_0
- ncurses=5.9=10
- notebook=4.3.1=py36_0
- numpy=1.12.0=py36_0
- openssl=1.0.2k=0
- pandas=0.19.2=np112py36_1
- pandoc=1.15.0.6=0
- pandocfilters=1.4.1=py36_0
- pango=1.40.3=1
- path.py=10.0=py36_0
- pcre=8.39=1
- pexpect=4.2.1=py36_0
- pickleshare=0.7.4=py36_0
- pip=9.0.1=py36_1
- pixman=0.34.0=0
- prompt_toolkit=1.0.9=py36_0
- ptyprocess=0.5.1=py36_0
- pygments=2.1.3=py36_0
- pyqt=5.6.0=py36_2
- python=3.6.0=0
- python-dateutil=2.6.0=py36_0
- pytz=2016.10=py36_0
- pyzmq=16.0.2=py36_0
- qt=5.6.2=3
- qtconsole=4.2.1=py36_1
- r::r-assertthat=0.1=r3.3.2_4
- r::r-backports=1.0.4=r3.3.2_0
- r::r-base=3.3.2=1
- r::r-base64enc=0.1_3=r3.3.2_0
- r::r-bh=1.62.0_1=r3.3.2_0
- r::r-bitops=1.0_6=r3.3.2_2
- r::r-boot=1.3_18=r3.3.2_0
- r::r-broom=0.4.1=r3.3.2_0
- r::r-car=2.1_4=r3.3.2_0
- r::r-caret=6.0_73=r3.3.2_0
- r::r-catools=1.17.1=r3.3.2_2
- r::r-class=7.3_14=r3.3.2_0
- r::r-cluster=2.0.5=r3.3.2_0
- r::r-codetools=0.2_15=r3.3.2_0
- r::r-colorspace=1.3_1=r3.3.2_0
- r::r-crayon=1.3.2=r3.3.2_0
- r::r-curl=2.3=r3.3.2_0
- r::r-data.table=1.10.0=r3.3.2_0
- r::r-dbi=0.5_1=r3.3.2_0
- r::r-dichromat=2.0_0=r3.3.2_2
- r::r-digest=0.6.10=r3.3.2_0
- r::r-dplyr=0.5.0=r3.3.2_0
- r::r-essentials=1.5.2=r3.3.2_0
- r::r-evaluate=0.10=r3.3.2_0
- r::r-forcats=0.1.1=r3.3.2_0
- r::r-foreach=1.4.3=r3.3.2_0
- r::r-foreign=0.8_67=r3.3.2_0
- r::r-formatr=1.4=r3.3.2_0
- r::r-ggplot2=2.2.0=r3.3.2_0
- r::r-gistr=0.3.6=r3.3.2_0
- r::r-glmnet=2.0_5=r3.3.2_0
- r::r-gtable=0.2.0=r3.3.2_0
- r::r-haven=1.0.0=r3.3.2_0
- r::r-hexbin=1.27.1=r3.3.2_0
- r::r-highr=0.6=r3.3.2_0
- r::r-hms=0.3=r3.3.2_0
- r::r-htmltools=0.3.5=r3.3.2_0
- r::r-htmlwidgets=0.8=r3.3.2_0
- r::r-httpuv=1.3.3=r3.3.2_0
- r::r-httr=1.2.1=r3.3.2_0
- r::r-irdisplay=0.4.4=r3.3.2_0
- r::r-irkernel=0.7.1=r3.3.2_0
- r::r-iterators=1.0.8=r3.3.2_0
- r::r-jsonlite=1.1=r3.3.2_0
- r::r-kernsmooth=2.23_15=r3.3.2_0
- r::r-knitr=1.15.1=r3.3.2_0
- r::r-labeling=0.3=r3.3.2_2
- r::r-lattice=0.20_34=r3.3.2_0
- r::r-lazyeval=0.2.0=r3.3.2_0
- r::r-lme4=1.1_12=r3.3.2_0
- r::r-lubridate=1.6.0=r3.3.2_0
- r::r-magrittr=1.5=r3.3.2_2
- r::r-maps=3.1.1=r3.3.2_0
- r::r-markdown=0.7.7=r3.3.2_2
- r::r-mass=7.3_45=r3.3.2_0
- r::r-matrix=1.2_7.1=r3.3.2_0
- r::r-matrixmodels=0.4_1=r3.3.2_0
- r::r-mgcv=1.8_16=r3.3.2_0
- r::r-mime=0.5=r3.3.2_0
- r::r-minqa=1.2.4=r3.3.2_2
- r::r-mnormt=1.5_5=r3.3.2_0
- r::r-modelmetrics=1.1.0=r3.3.2_0
- r::r-modelr=0.1.0=r3.3.2_0
- r::r-munsell=0.4.3=r3.3.2_0
- r::r-nlme=3.1_128=r3.3.2_0
- r::r-nloptr=1.0.4=r3.3.2_2
- r::r-nnet=7.3_12=r3.3.2_0
- r::r-openssl=0.9.5=r3.3.2_0
- r::r-pbdzmq=0.2_4=r3.3.2_0
- r::r-pbkrtest=0.4_6=r3.3.2_0
- r::r-plyr=1.8.4=r3.3.2_0
- r::r-pryr=0.1.2=r3.3.2_0
- r::r-psych=1.6.9=r3.3.2_0
- r::r-purrr=0.2.2=r3.3.2_0
- r::r-quantmod=0.4_7=r3.3.2_0
- r::r-quantreg=5.29=r3.3.2_0
- r::r-r6=2.2.0=r3.3.2_0
- r::r-randomforest=4.6_12=r3.3.2_0
- r::r-rbokeh=0.5.0=r3.3.2_0
- r::r-rcolorbrewer=1.1_2=r3.3.2_3
- r::r-rcpp=0.12.8=r3.3.2_0
- r::r-rcppeigen=0.3.2.9.0=r3.3.2_0
- r::r-readr=1.0.0=r3.3.2_0
- r::r-readxl=0.1.1=r3.3.2_0
- r::r-recommended=3.3.2=r3.3.2_0
- r::r-repr=0.10=r3.3.2_0
- r::r-reshape2=1.4.2=r3.3.2_0
- r::r-rmarkdown=1.3=r3.3.2_0
- r::r-rpart=4.1_10=r3.3.2_0
- r::r-rprojroot=1.1=r3.3.2_0
- r::r-rvest=0.3.2=r3.3.2_0
- r::r-scales=0.4.1=r3.3.2_0
- r::r-selectr=0.3_0=r3.3.2_0
- r::r-shiny=0.14.2=r3.3.2_0
- r::r-sourcetools=0.1.5=r3.3.2_0
- r::r-sparsem=1.74=r3.3.2_0
- r::r-spatial=7.3_11=r3.3.2_0
- r::r-stringi=1.1.2=r3.3.2_0
- r::r-stringr=1.1.0=r3.3.2_0
- r::r-survival=2.40_1=r3.3.2_0
- r::r-tibble=1.2=r3.3.2_0
- r::r-tidyr=0.6.0=r3.3.2_0
- r::r-tidyverse=1.0.0=r3.3.2_0
- r::r-ttr=0.23_1=r3.3.2_0
- r::r-uuid=0.1_2=r3.3.2_0
- r::r-xml2=1.0.0=r3.3.2_0
- r::r-xtable=1.8_2=r3.3.2_0
- r::r-xts=0.9_7=r3.3.2_2
- r::r-yaml=2.1.14=r3.3.2_0
- r::r-zoo=1.7_13=r3.3.2_0
- readline=6.2=2
- requests=2.12.4=py36_0
- setuptools=27.2.0=py36_0
- simplegeneric=0.8.1=py36_1
- sip=4.18=py36_0
- six=1.10.0=py36_0
- sqlite=3.13.0=0
- terminado=0.6=py36_0
- testpath=0.3=py36_0
- tk=8.5.18=0
- tornado=4.4.2=py36_0
- traitlets=4.3.1=py36_0
- wcwidth=0.1.7=py36_0
- wheel=0.29.0=py36_0
- widgetsnbextension=1.2.6=py36_0
- xz=5.2.2=1
- zeromq=4.1.5=0
- zlib=1.2.8=3
- pip:
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.1
  - prompt-toolkit==1.0.9
  - tqdm==4.11.2
